WIP: Extend functionalities of the Upload component
supabase/ui pull request #257
Opened 2021-08-04 18:51 UTC by Dhaiwat10

## What kind of change does this PR introduce?
Extended the present functionality of the `Upload` component.

## What is the current behavior?
The `Upload' component didn't support 'tracking'/retrieval of the uploaded files.

## What is the new behavior?
• Added two props: files and setFiles which allow you to control the uploaded files using state from a parent component.

• Added previews for uploaded images in the story.

## Additional context
<img width="603" alt="image" src="https://user-images.githubusercontent.com/39617427/128238090-cabddbca-4938-410d-a2f2-f5d2e513ffa8.png">

2021-08-04 18:52 UTC, Dhaiwat10 commented
Planning to add the ability to delete any of the uploaded files. Let me know what you think.

2021-08-10 05:32 UTC, MildTomato commented on src/components/Upload/Upload.tsx
> +  const fileUpload = (e: any) => {
can you update the types to not use `any` ?

2021-08-10 05:32 UTC, MildTomato commented on src/components/Upload/Upload.tsx
> +    console.log(classes)
remove console logs

2021-08-10 05:33 UTC, MildTomato requested changes
looks good, just a couple of comments

2021-08-10 09:44 UTC, Dhaiwat10 commented
Done ✅

2021-08-13 00:49 UTC, MildTomato commented on src/components/Upload/Upload.tsx
> +    console.log(newFiles)
remove console logs 😄

2021-08-13 00:49 UTC, MildTomato requested changes
just some stray console logs

2021-08-13 17:35 UTC, Dhaiwat10 commented
classic commit 🙃

2021-08-16 15:27 UTC, MildTomato approved these changes

2021-08-16 15:28 UTC, merged

2021-08-18 12:06 UTC, kiwicopple commented
:tada: This PR is included in version 0.32.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@supabase/ui/v/0.32.4)
- [GitHub release](https://github.com/supabase/ui/releases/tag/v0.32.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: